steps:
# Etapa para construir a imagem Docker e armazená-la no Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/gin-prod-393923/meu-aplicativo:$COMMIT_SHA', '.']

# Etapa para adicionar uma tag adicional à imagem Docker
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/gin-prod-393923/meu-aplicativo:$COMMIT_SHA', 'gcr.io/gin-prod-393923/meu-aplicativo:latest']

# Etapa para fazer o push da imagem para o Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/gin-prod-393923/meu-aplicativo']

# Etapa para implantar a imagem no GKE
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - 'run'
  - '--filename=path/to/kubernetes/deployment.yaml'
  - '--image=gcr.io/gin-prod-393923/meu-aplicativo:$COMMIT_SHA'
  - '--image=gcr.io/gin-prod-393923/meu-aplicativo:latest' # Utilize a última tag aqui
  - '--location=us-central1-a' # Substitua pela localização do seu cluster GKE
  - '--cluster=cluster-gin' # Substitua pelo nome do seu cluster GKE
