apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: container-teste
              image: gcr.io/gin-prod/container-teste:latest
              command: ["python3", "teste.py"]
          restartPolicy: Never
