apiVersion: apps/v1
kind: Deployment
metadata:
  name: meu-aplicativo
spec:
  replicas: 3 # Número desejado de réplicas do aplicativo
  selector:
    matchLabels:
      app: meu-aplicativo
  template:
    metadata:
      labels:
        app: meu-aplicativo
    spec:
      containers:
      - name: meu-aplicativo
        image: meu-aplicativo:latest # Substitua "latest" pela tag da sua imagem Docker
        ports:
        - containerPort: 80 # Porta exposta pelo contêiner
        resources:
          limits:
            cpu: "0.5" # Limites de recursos de CPU para o contêiner
            memory: "512Mi" # Limites de recursos de memória para o contêiner
          requests:
            cpu: "0.2" # Requisições de recursos de CPU para o contêiner
            memory: "256Mi" # Requisições de recursos de memória para o contêiner
