name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9.2'  # Substitua por uma versão do Python 3.5 ou superior

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install google-github-actions/setup-gcloud  # Instala o plugin gcloud para GitHub Actions

    - name: Configure Google Cloud SDK
      env:
        CLOUDSDK_PYTHON: /home/juliana_marques/gcloud-env/bin/python3
      run: |
        gcloud auth activate-service-account sa-gin@gin-prod-393923.iam.gserviceaccount.com
        gcloud container clusters get-credentials cluster-gin --zone us-central1-a 
        kubectl config set-context --current --namespace=gin-space

    - name: Deploy to GKE
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
