name: Deploy CronJob to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        version: '360.0.0'
        service_account_key: ${{ secrets.GINSECRET }}
        project_id: gin-prod-393923
        export_default_credentials: true

    - name: Configure kubectl
      run: |
        gcloud container clusters get-credentials ${{ secrets.GCP_CLUSTER_NAME }} --zone us-central1-a
        kubectl version

    - name: Deploy CronJob
      run: kubectl apply -f /path/to/your/cronjob.yaml
